"""arXiv HTML (generated by LaTeXML) to blocks.

The page is reduced to the paper body: math becomes its LaTeX source, figures become their
captions and footnotes follow their paragraph. Docling's HTML parser then produces the same
document structure as for PDFs, so both share one chunker.
"""

import re
from functools import lru_cache
from io import BytesIO

from bs4 import BeautifulSoup, NavigableString, Tag
from docling.datamodel.base_models import DocumentStream, InputFormat
from docling.document_converter import DocumentConverter

from app.ingest.chunking import ParsedDocument
from app.ingest.docling_blocks import document_blocks, normalize_heading

_DISPLAYSTYLE = re.compile(r"\\displaystyle\b\s*")
_HEADINGS = ["h1", "h2", "h3", "h4", "h5", "h6"]
# Page furniture and LaTeXML error markers inside the article
_REMOVED = ".ltx_note, .ltx_pagination, .ltx_ERROR, img, svg, button, script, style"


@lru_cache(maxsize=1)
def _converter() -> DocumentConverter:
    return DocumentConverter(allowed_formats=[InputFormat.HTML])


def parse_arxiv_html(html: str, *, title: str, url: str) -> ParsedDocument:
    body, anchors = clean_latexml(html)
    stream = DocumentStream(name="paper.html", stream=BytesIO(body.encode("utf-8")))
    doc = _converter().convert(stream).document
    blocks = document_blocks(doc, title, anchors)
    if not blocks:
        raise ValueError(f"no text found in {url}")
    return ParsedDocument(title=title, blocks=blocks, locator=None, details={"source": url})


def clean_latexml(html: str) -> tuple[str, dict[str, str]]:
    """Returns the cleaned HTML and a map from heading text to the section's element id."""
    soup = BeautifulSoup(html, "lxml")
    article = soup.find("article", class_="ltx_document")
    if not isinstance(article, Tag):
        raise ValueError("not a LaTeXML paper")

    # Keep the abstract and the sections; drop title, authors, notes and the bibliography.
    for child in article.find_all(recursive=False):
        classes = child.get("class") or []
        keep = "ltx_abstract" in classes or (
            child.name == "section" and "ltx_bibliography" not in classes
        )
        if not keep:
            child.decompose()

    _replace_equations(soup, article)
    _replace_math(article)
    _replace_figures(soup, article)
    _move_footnotes(soup, article)
    _replace_listings(soup, article)
    for tag in article.select(_REMOVED):
        tag.decompose()
    # Citations and cross-references become plain text ("[13]", "section 3.2"); their
    # links point into the removed bibliography or elsewhere on the page.
    for cite in article.find_all("cite"):
        cite.replace_with(NavigableString(cite.get_text()))
    for link in article.find_all("a"):
        link.unwrap()

    anchors: dict[str, str] = {}
    for heading in article.find_all(_HEADINGS):
        container = heading.find_parent(["section", "div"])
        if container is not None and container.get("id"):
            anchors[normalize_heading(heading.get_text(" "))] = str(container["id"])
    return f"<html><body>{article.decode_contents()}</body></html>", anchors


def _latex(math: Tag) -> str:
    return _plain(_DISPLAYSTYLE.sub("", str(math.get("alttext", ""))))


def _plain(text: str) -> str:
    return " ".join(text.split())


def _paragraph(soup: BeautifulSoup, text: str) -> Tag:
    paragraph = soup.new_tag("p")
    paragraph.string = text
    return paragraph


def _replace_equations(soup: BeautifulSoup, article: Tag) -> None:
    """Numbered and aligned equations are layout tables; each row becomes a paragraph
    such as "$$...$$ (1)"."""
    for table in article.select("table.ltx_equation, table.ltx_equationgroup"):
        if article not in table.parents:
            continue  # part of a group that was already replaced
        paragraphs = []
        for row in table.find_all("tr"):
            latex = " ".join(filter(None, (_latex(math) for math in row.find_all("math"))))
            if not latex:
                continue
            tag = row.select_one(".ltx_tag_equation")
            number = f" {tag.get_text(strip=True)}" if tag else ""
            paragraphs.append(_paragraph(soup, f"$${latex}$${number}"))
        if paragraphs:
            table.replace_with(*paragraphs)
        else:
            table.decompose()


def _replace_math(article: Tag) -> None:
    for math in article.find_all("math"):
        latex = _latex(math)
        if not latex:
            math.decompose()
            continue
        delimiter = "$$" if math.get("display") == "block" else "$"
        math.replace_with(NavigableString(f"{delimiter}{latex}{delimiter}"))


def _replace_figures(soup: BeautifulSoup, article: Tag) -> None:
    """Images are dropped and their captions kept; table floats keep their tables."""
    for figure in article.find_all("figure"):
        if article not in figure.parents:
            continue  # inside a figure that was already replaced
        caption = figure.find("figcaption")
        replacement = []
        if caption is not None and (text := _plain(caption.get_text())):
            replacement.append(_paragraph(soup, text))
        if "ltx_table" in (figure.get("class") or []):
            replacement.extend(table.extract() for table in figure.select("table.ltx_tabular"))
        if replacement:
            figure.replace_with(*replacement)
        else:
            figure.decompose()


def _move_footnotes(soup: BeautifulSoup, article: Tag) -> None:
    """LaTeXML puts footnote text inside the sentence; move it after the paragraph."""
    for note in article.select("span.ltx_note.ltx_role_footnote"):
        content = note.select_one(".ltx_note_content")
        paragraph = note.find_parent("div", class_="ltx_para")
        text = ""
        if content is not None:
            for mark in content.select(".ltx_note_mark, .ltx_tag_note"):
                mark.decompose()
            text = _plain(content.get_text())
        note.decompose()
        if text and paragraph is not None:
            paragraph.insert_after(_paragraph(soup, f"Footnote: {text}"))


def _replace_listings(soup: BeautifulSoup, article: Tag) -> None:
    for listing in article.select("div.ltx_listing"):
        for extra in listing.select(".ltx_listing_data, .ltx_tag_listingline"):
            extra.decompose()
        lines = [
            line.get_text().replace("\xa0", " ") for line in listing.select(".ltx_listingline")
        ]
        code = soup.new_tag("code")
        code.string = "\n".join(lines).strip("\n")
        pre = soup.new_tag("pre")
        pre.append(code)
        listing.replace_with(pre)
