// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { addArxivPaper, answerQuestion, dependencies, editQuestion, generateQuestions, getAttempt, getDocument, getJob, getQuestion, gradeAgain, health, listAttempts, listDocuments, listQuestions, listTopics, type Options, practiceMap, practiceNext, practiceProgress, practiceStats, searchChunks, uploadDocument } from '../sdk.gen';
import type { AddArxivPaperData, AddArxivPaperError, AddArxivPaperResponse, AnswerQuestionData, AnswerQuestionError, AnswerQuestionResponse, DependenciesData, DependenciesResponse, EditQuestionData, EditQuestionError, EditQuestionResponse, GenerateQuestionsData, GenerateQuestionsError, GenerateQuestionsResponse, GetAttemptData, GetAttemptError, GetAttemptResponse, GetDocumentData, GetDocumentError, GetDocumentResponse, GetJobData, GetJobError, GetJobResponse, GetQuestionData, GetQuestionError, GetQuestionResponse, GradeAgainData, GradeAgainError, GradeAgainResponse, HealthData, HealthResponse, ListAttemptsData, ListAttemptsError, ListAttemptsResponse, ListDocumentsData, ListDocumentsResponse, ListQuestionsData, ListQuestionsError, ListQuestionsResponse, ListTopicsData, ListTopicsError, ListTopicsResponse, PracticeMapData, PracticeMapResponse, PracticeNextData, PracticeNextResponse, PracticeProgressData, PracticeProgressResponse, PracticeStatsData, PracticeStatsResponse, SearchChunksData, SearchChunksError, SearchChunksResponse, UploadDocumentData, UploadDocumentError, UploadDocumentResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const healthQueryKey = (options?: Options<HealthData>) => createQueryKey('health', options);

/**
 * Health
 *
 * The API process is up.
 */
export const healthOptions = (options?: Options<HealthData>) => queryOptions<HealthResponse, DefaultError, HealthResponse, ReturnType<typeof healthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await health({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: healthQueryKey(options)
});

export const dependenciesQueryKey = (options?: Options<DependenciesData>) => createQueryKey('dependencies', options);

/**
 * Dependencies
 *
 * Database, local models and cloud API keys (whether keys are set, never their values).
 */
export const dependenciesOptions = (options?: Options<DependenciesData>) => queryOptions<DependenciesResponse, DefaultError, DependenciesResponse, ReturnType<typeof dependenciesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await dependencies({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: dependenciesQueryKey(options)
});

/**
 * Upload Document
 *
 * Upload a PDF or a Jupyter notebook. Returns 202 while its ingestion job is pending.
 */
export const uploadDocumentMutation = (options?: Partial<Options<UploadDocumentData>>): UseMutationOptions<UploadDocumentResponse, UploadDocumentError, Options<UploadDocumentData>> => {
    const mutationOptions: UseMutationOptions<UploadDocumentResponse, UploadDocumentError, Options<UploadDocumentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await uploadDocument({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Add Arxiv Paper
 *
 * Add an arXiv paper by ID or URL. Returns 202 while its ingestion job is pending.
 */
export const addArxivPaperMutation = (options?: Partial<Options<AddArxivPaperData>>): UseMutationOptions<AddArxivPaperResponse, AddArxivPaperError, Options<AddArxivPaperData>> => {
    const mutationOptions: UseMutationOptions<AddArxivPaperResponse, AddArxivPaperError, Options<AddArxivPaperData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await addArxivPaper({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listDocumentsQueryKey = (options?: Options<ListDocumentsData>) => createQueryKey('listDocuments', options);

/**
 * List Documents
 */
export const listDocumentsOptions = (options?: Options<ListDocumentsData>) => queryOptions<ListDocumentsResponse, DefaultError, ListDocumentsResponse, ReturnType<typeof listDocumentsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listDocuments({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listDocumentsQueryKey(options)
});

export const getDocumentQueryKey = (options: Options<GetDocumentData>) => createQueryKey('getDocument', options);

/**
 * Get Document
 */
export const getDocumentOptions = (options: Options<GetDocumentData>) => queryOptions<GetDocumentResponse, GetDocumentError, GetDocumentResponse, ReturnType<typeof getDocumentQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getDocument({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getDocumentQueryKey(options)
});

export const getJobQueryKey = (options: Options<GetJobData>) => createQueryKey('getJob', options);

/**
 * Get Job
 */
export const getJobOptions = (options: Options<GetJobData>) => queryOptions<GetJobResponse, GetJobError, GetJobResponse, ReturnType<typeof getJobQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getJob({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getJobQueryKey(options)
});

export const searchChunksQueryKey = (options: Options<SearchChunksData>) => createQueryKey('searchChunks', options);

/**
 * Search Chunks
 *
 * Search all ingested material. `mode=vector` or `mode=keyword` runs a single retriever.
 */
export const searchChunksOptions = (options: Options<SearchChunksData>) => queryOptions<SearchChunksResponse, SearchChunksError, SearchChunksResponse, ReturnType<typeof searchChunksQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await searchChunks({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: searchChunksQueryKey(options)
});

/**
 * Generate Questions
 *
 * Plan a batch of questions and queue it. Returns 202 with the job the worker will run.
 *
 * One batch at a time: while a job is still queued or running it is returned unchanged,
 * since a second plan made now would pick the same passages and pay for them twice.
 */
export const generateQuestionsMutation = (options?: Partial<Options<GenerateQuestionsData>>): UseMutationOptions<GenerateQuestionsResponse, GenerateQuestionsError, Options<GenerateQuestionsData>> => {
    const mutationOptions: UseMutationOptions<GenerateQuestionsResponse, GenerateQuestionsError, Options<GenerateQuestionsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await generateQuestions({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listQuestionsQueryKey = (options?: Options<ListQuestionsData>) => createQueryKey('listQuestions', options);

/**
 * List Questions
 *
 * The questions in the library, newest first. Every filter is optional.
 */
export const listQuestionsOptions = (options?: Options<ListQuestionsData>) => queryOptions<ListQuestionsResponse, ListQuestionsError, ListQuestionsResponse, ReturnType<typeof listQuestionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listQuestions({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listQuestionsQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const listQuestionsInfiniteQueryKey = (options?: Options<ListQuestionsData>): QueryKey<Options<ListQuestionsData>> => createQueryKey('listQuestions', options, true);

/**
 * List Questions
 *
 * The questions in the library, newest first. Every filter is optional.
 */
export const listQuestionsInfiniteOptions = (options?: Options<ListQuestionsData>) => {
    const opts = infiniteQueryOptions<ListQuestionsResponse, ListQuestionsError, InfiniteData<ListQuestionsResponse>, QueryKey<Options<ListQuestionsData>>, number | Pick<QueryKey<Options<ListQuestionsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<ListQuestionsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await listQuestions({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listQuestionsInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

export const getQuestionQueryKey = (options: Options<GetQuestionData>) => createQueryKey('getQuestion', options);

/**
 * Get Question
 *
 * One question with its sources, key points and validation report.
 */
export const getQuestionOptions = (options: Options<GetQuestionData>) => queryOptions<GetQuestionResponse, GetQuestionError, GetQuestionResponse, ReturnType<typeof getQuestionQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getQuestion({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getQuestionQueryKey(options)
});

/**
 * Edit Question
 *
 * Correct a question, or retire it from the library and put it back.
 *
 * Key points are replaced as a whole, and every quote has to be in the passage it names, as
 * in generation; one that is not is refused with 422 and nothing changes. A new question
 * text is embedded again for the duplicate check. While the local embedding model is away
 * the old embedding is cleared instead, so the check passes over the question rather than
 * compare against words it no longer has. Each change is kept in the question's report with
 * what it replaced; a change to what the question already says is no change at all.
 */
export const editQuestionMutation = (options?: Partial<Options<EditQuestionData>>): UseMutationOptions<EditQuestionResponse, EditQuestionError, Options<EditQuestionData>> => {
    const mutationOptions: UseMutationOptions<EditQuestionResponse, EditQuestionError, Options<EditQuestionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await editQuestion({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listTopicsQueryKey = (options?: Options<ListTopicsData>) => createQueryKey('listTopics', options);

/**
 * List Topics
 *
 * The topic map, the topics with the most passages behind them first.
 */
export const listTopicsOptions = (options?: Options<ListTopicsData>) => queryOptions<ListTopicsResponse, ListTopicsError, ListTopicsResponse, ReturnType<typeof listTopicsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listTopics({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listTopicsQueryKey(options)
});

export const listTopicsInfiniteQueryKey = (options?: Options<ListTopicsData>): QueryKey<Options<ListTopicsData>> => createQueryKey('listTopics', options, true);

/**
 * List Topics
 *
 * The topic map, the topics with the most passages behind them first.
 */
export const listTopicsInfiniteOptions = (options?: Options<ListTopicsData>) => {
    const opts = infiniteQueryOptions<ListTopicsResponse, ListTopicsError, InfiniteData<ListTopicsResponse>, QueryKey<Options<ListTopicsData>>, number | Pick<QueryKey<Options<ListTopicsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<ListTopicsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await listTopics({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listTopicsInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

export const listAttemptsQueryKey = (options: Options<ListAttemptsData>) => createQueryKey('listAttempts', options);

/**
 * List Attempts
 *
 * The answers given to a question, newest first.
 */
export const listAttemptsOptions = (options: Options<ListAttemptsData>) => queryOptions<ListAttemptsResponse, ListAttemptsError, ListAttemptsResponse, ReturnType<typeof listAttemptsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listAttempts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listAttemptsQueryKey(options)
});

export const listAttemptsInfiniteQueryKey = (options: Options<ListAttemptsData>): QueryKey<Options<ListAttemptsData>> => createQueryKey('listAttempts', options, true);

/**
 * List Attempts
 *
 * The answers given to a question, newest first.
 */
export const listAttemptsInfiniteOptions = (options: Options<ListAttemptsData>) => {
    const opts = infiniteQueryOptions<ListAttemptsResponse, ListAttemptsError, InfiniteData<ListAttemptsResponse>, QueryKey<Options<ListAttemptsData>>, number | Pick<QueryKey<Options<ListAttemptsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
    // @ts-ignore
    {
        queryFn: async ({ pageParam, queryKey, signal }) => {
            // @ts-ignore
            const page: Pick<QueryKey<Options<ListAttemptsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
                query: {
                    offset: pageParam
                }
            };
            const params = createInfiniteParams(queryKey, page);
            const { data } = await listAttempts({
                ...options,
                ...params,
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listAttemptsInfiniteQueryKey(options)
    });
    return opts as Omit<typeof opts, 'initialData'>;
};

/**
 * Answer Question
 *
 * Answer a question, have the answer graded, and reschedule the question. Only questions
 * in the library can be answered: one that was rejected or retired is not there to practise.
 */
export const answerQuestionMutation = (options?: Partial<Options<AnswerQuestionData>>): UseMutationOptions<AnswerQuestionResponse, AnswerQuestionError, Options<AnswerQuestionData>> => {
    const mutationOptions: UseMutationOptions<AnswerQuestionResponse, AnswerQuestionError, Options<AnswerQuestionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await answerQuestion({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Grade Again
 *
 * Grade an attempt again, after a failed grade or with a changed grader. Every earlier
 * grade is kept. The first successful grade reschedules the question; later ones don't.
 */
export const gradeAgainMutation = (options?: Partial<Options<GradeAgainData>>): UseMutationOptions<GradeAgainResponse, GradeAgainError, Options<GradeAgainData>> => {
    const mutationOptions: UseMutationOptions<GradeAgainResponse, GradeAgainError, Options<GradeAgainData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await gradeAgain({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAttemptQueryKey = (options: Options<GetAttemptData>) => createQueryKey('getAttempt', options);

/**
 * Get Attempt
 *
 * One attempt with every grade it was given.
 */
export const getAttemptOptions = (options: Options<GetAttemptData>) => queryOptions<GetAttemptResponse, GetAttemptError, GetAttemptResponse, ReturnType<typeof getAttemptQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAttempt({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAttemptQueryKey(options)
});

export const practiceNextQueryKey = (options?: Options<PracticeNextData>) => createQueryKey('practiceNext', options);

/**
 * Practice Next
 *
 * The question to practise next, without its answer, and why it was picked.
 */
export const practiceNextOptions = (options?: Options<PracticeNextData>) => queryOptions<PracticeNextResponse, DefaultError, PracticeNextResponse, ReturnType<typeof practiceNextQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await practiceNext({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: practiceNextQueryKey(options)
});

export const practiceProgressQueryKey = (options?: Options<PracticeProgressData>) => createQueryKey('practiceProgress', options);

/**
 * Practice Progress
 *
 * XP, level, streak and coins, worked out from every graded answer.
 */
export const practiceProgressOptions = (options?: Options<PracticeProgressData>) => queryOptions<PracticeProgressResponse, DefaultError, PracticeProgressResponse, ReturnType<typeof practiceProgressQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await practiceProgress({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: practiceProgressQueryKey(options)
});

export const practiceMapQueryKey = (options?: Options<PracticeMapData>) => createQueryKey('practiceMap', options);

/**
 * Practice Map
 *
 * The labyrinth on the dashboard: a room for each topic with questions in the library,
 * how well it is known and what is due in it, the passages between the rooms, today's
 * thread through them, and the Minotaur's room, the weakest.
 */
export const practiceMapOptions = (options?: Options<PracticeMapData>) => queryOptions<PracticeMapResponse, DefaultError, PracticeMapResponse, ReturnType<typeof practiceMapQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await practiceMap({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: practiceMapQueryKey(options)
});

export const practiceStatsQueryKey = (options?: Options<PracticeStatsData>) => createQueryKey('practiceStats', options);

/**
 * Practice Stats
 *
 * The dashboard's charts: the latest scores, the days practised, and what comes due.
 */
export const practiceStatsOptions = (options?: Options<PracticeStatsData>) => queryOptions<PracticeStatsResponse, DefaultError, PracticeStatsResponse, ReturnType<typeof practiceStatsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await practiceStats({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: practiceStatsQueryKey(options)
});
