// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { AddArxivPaperData, AddArxivPaperErrors, AddArxivPaperResponses, AddRatingData, AddRatingErrors, AddRatingResponses, AnswerQuestionData, AnswerQuestionErrors, AnswerQuestionResponses, DependenciesData, DependenciesResponses, EditQuestionData, EditQuestionErrors, EditQuestionResponses, GenerateQuestionsData, GenerateQuestionsErrors, GenerateQuestionsResponses, GetAttemptData, GetAttemptErrors, GetAttemptResponses, GetDocumentData, GetDocumentErrors, GetDocumentResponses, GetJobData, GetJobErrors, GetJobResponses, GetQuestionData, GetQuestionErrors, GetQuestionResponses, GradeAgainData, GradeAgainErrors, GradeAgainResponses, HealthData, HealthResponses, ListAttemptsData, ListAttemptsErrors, ListAttemptsResponses, ListDocumentsData, ListDocumentsResponses, ListQuestionsData, ListQuestionsErrors, ListQuestionsResponses, ListTopicsData, ListTopicsErrors, ListTopicsResponses, PracticeMapData, PracticeMapResponses, PracticeNextData, PracticeNextResponses, PracticeProgressData, PracticeProgressResponses, PracticeStatsData, PracticeStatsResponses, SearchChunksData, SearchChunksErrors, SearchChunksResponses, UploadDocumentData, UploadDocumentErrors, UploadDocumentResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Health
 *
 * The API process is up.
 */
export const health = <ThrowOnError extends boolean = false>(options?: Options<HealthData, ThrowOnError>): RequestResult<HealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Dependencies
 *
 * Database, local models and cloud API keys (whether keys are set, never their values).
 */
export const dependencies = <ThrowOnError extends boolean = false>(options?: Options<DependenciesData, ThrowOnError>): RequestResult<DependenciesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<DependenciesResponses, unknown, ThrowOnError>({ url: '/health/deps', ...options });

/**
 * Upload Document
 *
 * Upload a PDF or a Jupyter notebook. Returns 202 while its ingestion job is pending.
 */
export const uploadDocument = <ThrowOnError extends boolean = false>(options: Options<UploadDocumentData, ThrowOnError>): RequestResult<UploadDocumentResponses, UploadDocumentErrors, ThrowOnError> => (options.client ?? client).post<UploadDocumentResponses, UploadDocumentErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/documents/upload',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Add Arxiv Paper
 *
 * Add an arXiv paper by ID or URL. Returns 202 while its ingestion job is pending.
 */
export const addArxivPaper = <ThrowOnError extends boolean = false>(options: Options<AddArxivPaperData, ThrowOnError>): RequestResult<AddArxivPaperResponses, AddArxivPaperErrors, ThrowOnError> => (options.client ?? client).post<AddArxivPaperResponses, AddArxivPaperErrors, ThrowOnError>({
    url: '/documents/arxiv',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Documents
 */
export const listDocuments = <ThrowOnError extends boolean = false>(options?: Options<ListDocumentsData, ThrowOnError>): RequestResult<ListDocumentsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListDocumentsResponses, unknown, ThrowOnError>({ url: '/documents', ...options });

/**
 * Get Document
 */
export const getDocument = <ThrowOnError extends boolean = false>(options: Options<GetDocumentData, ThrowOnError>): RequestResult<GetDocumentResponses, GetDocumentErrors, ThrowOnError> => (options.client ?? client).get<GetDocumentResponses, GetDocumentErrors, ThrowOnError>({ url: '/documents/{document_id}', ...options });

/**
 * Get Job
 */
export const getJob = <ThrowOnError extends boolean = false>(options: Options<GetJobData, ThrowOnError>): RequestResult<GetJobResponses, GetJobErrors, ThrowOnError> => (options.client ?? client).get<GetJobResponses, GetJobErrors, ThrowOnError>({ url: '/jobs/{job_id}', ...options });

/**
 * Search Chunks
 *
 * Search all ingested material. `mode=vector` or `mode=keyword` runs a single retriever.
 */
export const searchChunks = <ThrowOnError extends boolean = false>(options: Options<SearchChunksData, ThrowOnError>): RequestResult<SearchChunksResponses, SearchChunksErrors, ThrowOnError> => (options.client ?? client).get<SearchChunksResponses, SearchChunksErrors, ThrowOnError>({ url: '/search', ...options });

/**
 * Generate Questions
 *
 * Plan a batch of questions and queue it. Returns 202 with the job the worker will run.
 *
 * One batch at a time: while a job is still queued or running it is returned unchanged,
 * since a second plan made now would pick the same passages and pay for them twice.
 */
export const generateQuestions = <ThrowOnError extends boolean = false>(options: Options<GenerateQuestionsData, ThrowOnError>): RequestResult<GenerateQuestionsResponses, GenerateQuestionsErrors, ThrowOnError> => (options.client ?? client).post<GenerateQuestionsResponses, GenerateQuestionsErrors, ThrowOnError>({
    url: '/questions/generate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Questions
 *
 * The questions in the library, newest first. Every filter is optional.
 */
export const listQuestions = <ThrowOnError extends boolean = false>(options?: Options<ListQuestionsData, ThrowOnError>): RequestResult<ListQuestionsResponses, ListQuestionsErrors, ThrowOnError> => (options?.client ?? client).get<ListQuestionsResponses, ListQuestionsErrors, ThrowOnError>({ url: '/questions', ...options });

/**
 * Get Question
 *
 * One question with its sources, key points and validation report.
 */
export const getQuestion = <ThrowOnError extends boolean = false>(options: Options<GetQuestionData, ThrowOnError>): RequestResult<GetQuestionResponses, GetQuestionErrors, ThrowOnError> => (options.client ?? client).get<GetQuestionResponses, GetQuestionErrors, ThrowOnError>({ url: '/questions/{question_id}', ...options });

/**
 * Edit Question
 *
 * Correct a question, or retire it from the library and put it back.
 *
 * Key points are replaced as a whole, and every quote has to be in the passage it names, as
 * in generation; one that is not is refused with 422 and nothing changes. A new question
 * text is embedded again for the duplicate check. While the local embedding model is away
 * the old embedding is cleared instead, so the check passes over the question rather than
 * compare against words it no longer has. Each change is kept in the question's report with
 * what it replaced; a change to what the question already says is no change at all.
 */
export const editQuestion = <ThrowOnError extends boolean = false>(options: Options<EditQuestionData, ThrowOnError>): RequestResult<EditQuestionResponses, EditQuestionErrors, ThrowOnError> => (options.client ?? client).patch<EditQuestionResponses, EditQuestionErrors, ThrowOnError>({
    url: '/questions/{question_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Topics
 *
 * The topic map, the topics with the most passages behind them first.
 */
export const listTopics = <ThrowOnError extends boolean = false>(options?: Options<ListTopicsData, ThrowOnError>): RequestResult<ListTopicsResponses, ListTopicsErrors, ThrowOnError> => (options?.client ?? client).get<ListTopicsResponses, ListTopicsErrors, ThrowOnError>({ url: '/topics', ...options });

/**
 * List Attempts
 *
 * The answers given to a question, newest first.
 */
export const listAttempts = <ThrowOnError extends boolean = false>(options: Options<ListAttemptsData, ThrowOnError>): RequestResult<ListAttemptsResponses, ListAttemptsErrors, ThrowOnError> => (options.client ?? client).get<ListAttemptsResponses, ListAttemptsErrors, ThrowOnError>({ url: '/questions/{question_id}/attempts', ...options });

/**
 * Answer Question
 *
 * Answer a question, have the answer graded, and reschedule the question. Only questions
 * in the library can be answered: one that was rejected or retired is not there to practise.
 */
export const answerQuestion = <ThrowOnError extends boolean = false>(options: Options<AnswerQuestionData, ThrowOnError>): RequestResult<AnswerQuestionResponses, AnswerQuestionErrors, ThrowOnError> => (options.client ?? client).post<AnswerQuestionResponses, AnswerQuestionErrors, ThrowOnError>({
    url: '/questions/{question_id}/attempts',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Grade Again
 *
 * Grade an attempt again, after a failed grade or with a changed grader. Every earlier
 * grade is kept. The first successful grade reschedules the question; later ones don't.
 */
export const gradeAgain = <ThrowOnError extends boolean = false>(options: Options<GradeAgainData, ThrowOnError>): RequestResult<GradeAgainResponses, GradeAgainErrors, ThrowOnError> => (options.client ?? client).post<GradeAgainResponses, GradeAgainErrors, ThrowOnError>({ url: '/attempts/{attempt_id}/grades', ...options });

/**
 * Get Attempt
 *
 * One attempt with every grade it was given.
 */
export const getAttempt = <ThrowOnError extends boolean = false>(options: Options<GetAttemptData, ThrowOnError>): RequestResult<GetAttemptResponses, GetAttemptErrors, ThrowOnError> => (options.client ?? client).get<GetAttemptResponses, GetAttemptErrors, ThrowOnError>({ url: '/attempts/{attempt_id}', ...options });

/**
 * Practice Next
 *
 * The question to practise next, without its answer, and why it was picked.
 */
export const practiceNext = <ThrowOnError extends boolean = false>(options?: Options<PracticeNextData, ThrowOnError>): RequestResult<PracticeNextResponses, unknown, ThrowOnError> => (options?.client ?? client).get<PracticeNextResponses, unknown, ThrowOnError>({ url: '/practice/next', ...options });

/**
 * Practice Progress
 *
 * XP, level, streak and coins, worked out from every graded answer.
 */
export const practiceProgress = <ThrowOnError extends boolean = false>(options?: Options<PracticeProgressData, ThrowOnError>): RequestResult<PracticeProgressResponses, unknown, ThrowOnError> => (options?.client ?? client).get<PracticeProgressResponses, unknown, ThrowOnError>({ url: '/practice/progress', ...options });

/**
 * Practice Map
 *
 * The labyrinth on the dashboard: a room for each topic with questions in the library,
 * how well it is known and what is due in it, the passages between the rooms, today's
 * thread through them, and the Minotaur's room, the weakest.
 */
export const practiceMap = <ThrowOnError extends boolean = false>(options?: Options<PracticeMapData, ThrowOnError>): RequestResult<PracticeMapResponses, unknown, ThrowOnError> => (options?.client ?? client).get<PracticeMapResponses, unknown, ThrowOnError>({ url: '/practice/map', ...options });

/**
 * Practice Stats
 *
 * The dashboard's charts: the latest scores, the days practised, and what comes due.
 */
export const practiceStats = <ThrowOnError extends boolean = false>(options?: Options<PracticeStatsData, ThrowOnError>): RequestResult<PracticeStatsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<PracticeStatsResponses, unknown, ThrowOnError>({ url: '/practice/stats', ...options });

/**
 * Add Rating
 *
 * Rate a question good or poor, or a grade fair or unfair, with an optional note on why.
 *
 * A rating never replaces an earlier one; the latest is the one that stands. Any question
 * can be rated, whatever its status: a rejected question rated good is a check that turned
 * down too much. A grade can be rated once it has graded the answer: a failed grade has no
 * verdict to judge.
 */
export const addRating = <ThrowOnError extends boolean = false>(options: Options<AddRatingData, ThrowOnError>): RequestResult<AddRatingResponses, AddRatingErrors, ThrowOnError> => (options.client ?? client).post<AddRatingResponses, AddRatingErrors, ThrowOnError>({
    url: '/ratings',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
