// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AnswerIn
 */
export type AnswerIn = {
    /**
     * Answer
     */
    answer: string;
    /**
     * Seconds
     */
    seconds?: number | null;
    /**
     * Time Limit
     */
    time_limit?: number | null;
};

/**
 * ArxivIn
 */
export type ArxivIn = {
    /**
     * Ocr
     *
     * Recognize text in scanned pages (PDF only)
     */
    ocr?: boolean;
    /**
     * Formulas
     *
     * Convert equations to LaTeX (PDF only; slower)
     */
    formulas?: boolean;
    /**
     * Force
     *
     * Ingest again even if the document is ready
     */
    force?: boolean;
    /**
     * Arxiv Id
     */
    arxiv_id: string;
};

/**
 * AttemptOut
 */
export type AttemptOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Question Id
     */
    question_id: number;
    /**
     * Question
     */
    question: string;
    /**
     * Answer
     */
    answer: string;
    /**
     * Seconds
     */
    seconds: number | null;
    /**
     * Time Limit
     */
    time_limit: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Grades
     */
    grades: Array<GradeOut>;
    review: ReviewOut | null;
    earned: EarnedOut | null;
};

/**
 * Body_upload_document
 */
export type BodyUploadDocument = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Check
 */
export type Check = {
    /**
     * Name
     */
    name: string;
    /**
     * Status
     */
    status: 'ok' | 'warn' | 'fail';
    /**
     * Detail
     */
    detail: string;
};

/**
 * ClaimOut
 */
export type ClaimOut = {
    /**
     * Claim
     */
    claim: string;
    /**
     * Verdict
     */
    verdict: string;
    /**
     * Why
     */
    why: string;
    /**
     * Chunk Id
     */
    chunk_id: number | null;
    /**
     * Citation
     */
    citation: string | null;
    /**
     * Link
     */
    link: string | null;
};

/**
 * CoinOut
 */
export type CoinOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Glyph
     */
    glyph: string;
    /**
     * Condition
     */
    condition: string;
    /**
     * Minted On
     */
    minted_on: string | null;
    /**
     * Have
     */
    have: number | null;
    /**
     * Need
     */
    need: number | null;
};

/**
 * DayCountOut
 */
export type DayCountOut = {
    /**
     * Day
     */
    day: string;
    /**
     * Count
     */
    count: number;
};

/**
 * DocumentOut
 */
export type DocumentOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Source Type
     */
    source_type: string;
    /**
     * Title
     */
    title: string;
    /**
     * Authors
     */
    authors: string | null;
    /**
     * Filename
     */
    filename: string | null;
    /**
     * Arxiv Id
     */
    arxiv_id: string | null;
    /**
     * Arxiv Version
     */
    arxiv_version: string | null;
    /**
     * License
     */
    license: string | null;
    /**
     * Url
     */
    url: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Error
     */
    error: string | null;
    /**
     * Details
     */
    details: {
        [key: string]: unknown;
    };
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Chunk Count
     */
    chunk_count?: number;
    /**
     * Tagged Count
     */
    tagged_count?: number;
    latest_job?: JobOut | null;
};

/**
 * EarnedOut
 */
export type EarnedOut = {
    /**
     * Xp
     */
    xp: number;
    parts: XpOut;
    /**
     * Total Xp
     */
    total_xp: number;
    level: LevelOut;
    /**
     * Level Up
     */
    level_up: boolean;
    /**
     * Streak
     */
    streak: number;
    /**
     * Coins
     */
    coins: Array<CoinOut>;
};

/**
 * GenerateIn
 */
export type GenerateIn = {
    /**
     * Count
     *
     * How many questions to write
     */
    count?: number;
    /**
     * Document Id
     *
     * Ask about one document only
     */
    document_id?: number | null;
};

/**
 * GenerateOut
 */
export type GenerateOut = {
    /**
     * Message
     */
    message: string;
    /**
     * Planned
     */
    planned: number;
    job: JobOut | null;
};

/**
 * GradeOut
 */
export type GradeOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Status
     */
    status: string;
    /**
     * Error
     */
    error: string | null;
    /**
     * Grader Model
     */
    grader_model: string | null;
    /**
     * Prompt Version
     */
    prompt_version: string;
    /**
     * Score
     */
    score: number | null;
    /**
     * Coverage
     */
    coverage: number | null;
    /**
     * Contradicted
     */
    contradicted: number | null;
    /**
     * Clarity
     */
    clarity: number | null;
    /**
     * Key Points
     */
    key_points: Array<KeyPointGradeOut>;
    /**
     * Claims
     */
    claims: Array<ClaimOut>;
    /**
     * Strengths
     */
    strengths: Array<string>;
    /**
     * Gaps
     */
    gaps: Array<string>;
    /**
     * Errors
     */
    errors: Array<string>;
    /**
     * Improved Answer
     */
    improved_answer: string | null;
    /**
     * Follow Up
     */
    follow_up: string | null;
    /**
     * Usage
     */
    usage: {
        [key: string]: unknown;
    };
    /**
     * Seconds
     */
    seconds: number | null;
    /**
     * Created At
     */
    created_at: string;
    rating: RatingOut | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IngestOut
 */
export type IngestOut = {
    /**
     * Message
     */
    message: string;
    document: DocumentOut;
    job: JobOut | null;
};

/**
 * JobOut
 */
export type JobOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Kind
     */
    kind: string;
    /**
     * Document Id
     */
    document_id: number | null;
    /**
     * Status
     */
    status: string;
    /**
     * Progress
     */
    progress: string | null;
    /**
     * Error
     */
    error: string | null;
    /**
     * Attempts
     */
    attempts: number;
    /**
     * Options
     */
    options: {
        [key: string]: unknown;
    };
    /**
     * Created At
     */
    created_at: string;
    /**
     * Started At
     */
    started_at: string | null;
    /**
     * Finished At
     */
    finished_at: string | null;
};

/**
 * KeyPointGradeOut
 */
export type KeyPointGradeOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Text
     */
    text: string;
    /**
     * Weight
     */
    weight: number;
    /**
     * Status
     */
    status: string;
    /**
     * Answer Quote
     */
    answer_quote: string;
    /**
     * Quote Found
     */
    quote_found: boolean | null;
};

/**
 * KeyPointIn
 */
export type KeyPointIn = {
    /**
     * Text
     */
    text: string;
    /**
     * Weight
     *
     * How much of the answer the point carries
     */
    weight: 1 | 2 | 3;
    /**
     * Evidence Quote
     *
     * Six or more words copied from the passage, showing the point is there
     */
    evidence_quote: string;
    /**
     * Chunk Id
     *
     * The passage the quote is from: one of the sources
     */
    chunk_id: number;
};

/**
 * KeyPointOut
 */
export type KeyPointOut = {
    /**
     * Text
     */
    text: string;
    /**
     * Weight
     */
    weight: number;
    /**
     * Evidence Quote
     */
    evidence_quote: string;
    /**
     * Chunk Id
     */
    chunk_id?: number | null;
};

/**
 * LevelOut
 */
export type LevelOut = {
    /**
     * Number
     */
    number: number;
    /**
     * Name
     */
    name: string;
    /**
     * Of
     */
    of: number;
    /**
     * Start
     */
    start: number;
    /**
     * Next Start
     */
    next_start: number | null;
    /**
     * Next Name
     */
    next_name: string | null;
};

/**
 * MapOut
 */
export type MapOut = {
    /**
     * Columns
     */
    columns: number;
    /**
     * Rows
     */
    rows: number;
    /**
     * Rooms
     */
    rooms: Array<RoomOut>;
    /**
     * Passages
     */
    passages: Array<[
        number,
        number
    ]>;
    /**
     * Entrance
     */
    entrance: number | null;
    /**
     * Lair
     */
    lair: number | null;
    /**
     * Visits
     */
    visits: Array<number>;
    /**
     * Thread
     */
    thread: Array<number>;
};

/**
 * PracticeOut
 */
export type PracticeOut = {
    question: QuestionOut;
    /**
     * Reason
     */
    reason: 'due' | 'new' | 'ahead';
    /**
     * Why
     */
    why: string;
    /**
     * Due
     */
    due: string | null;
    /**
     * Recall
     */
    recall: number;
    /**
     * Topic Mastery
     */
    topic_mastery: number;
    /**
     * Due Count
     */
    due_count: number;
    /**
     * New Count
     */
    new_count: number;
};

/**
 * ProgressOut
 */
export type ProgressOut = {
    /**
     * Xp
     */
    xp: number;
    level: LevelOut;
    streak: StreakOut;
    /**
     * Answers
     */
    answers: number;
    /**
     * Coins
     */
    coins: Array<CoinOut>;
};

/**
 * QuestionDetailOut
 */
export type QuestionDetailOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Text
     */
    text: string;
    /**
     * Style
     */
    style: string;
    /**
     * Difficulty
     */
    difficulty: number;
    /**
     * Status
     */
    status: string;
    /**
     * Topic Id
     */
    topic_id: number | null;
    /**
     * Topic
     */
    topic: string | null;
    /**
     * Source Updated
     */
    source_updated: boolean;
    /**
     * Citations
     */
    citations: Array<string>;
    /**
     * Document Ids
     */
    document_ids: Array<number>;
    /**
     * Created At
     */
    created_at: string;
    rating: RatingOut | null;
    /**
     * Reference Answer
     */
    reference_answer: string;
    /**
     * Key Points
     */
    key_points: Array<KeyPointOut>;
    /**
     * Misconceptions
     */
    misconceptions: Array<string>;
    /**
     * Validation
     */
    validation: {
        [key: string]: unknown;
    };
    /**
     * Generator Model
     */
    generator_model: string;
    /**
     * Prompt Version
     */
    prompt_version: string;
    /**
     * Usage
     */
    usage: {
        [key: string]: unknown;
    };
    /**
     * Sources
     */
    sources: Array<SourceOut>;
};

/**
 * QuestionEditIn
 *
 * The changes to make to a question. A field left out stays as it is.
 */
export type QuestionEditIn = {
    /**
     * Text
     */
    text?: string | null;
    /**
     * Reference Answer
     */
    reference_answer?: string | null;
    /**
     * Key Points
     */
    key_points?: Array<KeyPointIn> | null;
    /**
     * Status
     */
    status?: 'accepted' | 'retired' | null;
    /**
     * Reason
     */
    reason?: string | null;
};

/**
 * QuestionOut
 */
export type QuestionOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Text
     */
    text: string;
    /**
     * Style
     */
    style: string;
    /**
     * Difficulty
     */
    difficulty: number;
    /**
     * Status
     */
    status: string;
    /**
     * Topic Id
     */
    topic_id: number | null;
    /**
     * Topic
     */
    topic: string | null;
    /**
     * Source Updated
     */
    source_updated: boolean;
    /**
     * Citations
     */
    citations: Array<string>;
    /**
     * Document Ids
     */
    document_ids: Array<number>;
    /**
     * Created At
     */
    created_at: string;
    rating: RatingOut | null;
};

/**
 * QuestionsOut
 */
export type QuestionsOut = {
    /**
     * Total
     */
    total: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
    /**
     * Results
     */
    results: Array<QuestionOut>;
};

/**
 * RatingIn
 *
 * A rating of one question or of one grade.
 */
export type RatingIn = {
    /**
     * Question Id
     *
     * The question rated; or give grade_id
     */
    question_id?: number | null;
    /**
     * Grade Id
     *
     * The grade rated; or give question_id
     */
    grade_id?: number | null;
    /**
     * Value
     *
     * 1 for a good question or a fair grade, -1 for a poor question or an unfair grade
     */
    value: 1 | -1;
    /**
     * Note
     *
     * Why, in a sentence
     */
    note?: string | null;
};

/**
 * RatingOut
 */
export type RatingOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Question Id
     */
    question_id: number | null;
    /**
     * Grade Id
     */
    grade_id: number | null;
    /**
     * Value
     */
    value: 1 | -1;
    /**
     * Note
     */
    note: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ReviewOut
 */
export type ReviewOut = {
    /**
     * Rating
     */
    rating: 'again' | 'hard' | 'good' | 'easy';
    /**
     * Day
     */
    day: string;
    /**
     * Due
     */
    due: string;
    /**
     * Interval
     */
    interval: number;
};

/**
 * RoomOut
 */
export type RoomOut = {
    /**
     * Topic Id
     */
    topic_id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Cell
     */
    cell: number;
    /**
     * Questions
     */
    questions: number;
    /**
     * Practised
     */
    practised: number;
    /**
     * Due
     */
    due: number;
    /**
     * Mastery
     */
    mastery: number;
};

/**
 * ScoreOut
 */
export type ScoreOut = {
    /**
     * Attempt Id
     */
    attempt_id: number;
    /**
     * Question Id
     */
    question_id: number;
    /**
     * Day
     */
    day: string;
    /**
     * Score
     */
    score: number;
};

/**
 * SearchHitOut
 */
export type SearchHitOut = {
    /**
     * Chunk Id
     */
    chunk_id: number;
    /**
     * Document Id
     */
    document_id: number;
    /**
     * Document Title
     */
    document_title: string;
    /**
     * Source Type
     */
    source_type: string;
    /**
     * Citation
     */
    citation: string;
    /**
     * Link
     */
    link: string | null;
    /**
     * Section
     */
    section: string | null;
    /**
     * Page Start
     */
    page_start: number | null;
    /**
     * Page End
     */
    page_end: number | null;
    /**
     * Cell Start
     */
    cell_start: number | null;
    /**
     * Cell End
     */
    cell_end: number | null;
    /**
     * Content Types
     */
    content_types: Array<string>;
    /**
     * Text
     */
    text: string;
    /**
     * Score
     */
    score: number;
    /**
     * Vector Rank
     */
    vector_rank: number | null;
    /**
     * Keyword Rank
     */
    keyword_rank: number | null;
};

/**
 * SearchOut
 */
export type SearchOut = {
    /**
     * Query
     */
    query: string;
    /**
     * Mode
     */
    mode: 'hybrid' | 'vector' | 'keyword';
    /**
     * Warning
     */
    warning: string | null;
    /**
     * Results
     */
    results: Array<SearchHitOut>;
};

/**
 * SourceOut
 */
export type SourceOut = {
    /**
     * Chunk Id
     */
    chunk_id: number;
    /**
     * Document Id
     */
    document_id: number;
    /**
     * Document Title
     */
    document_title: string;
    /**
     * Citation
     */
    citation: string;
    /**
     * Link
     */
    link: string | null;
    /**
     * Section
     */
    section: string | null;
    /**
     * Superseded
     */
    superseded: boolean;
    /**
     * Text
     */
    text: string;
};

/**
 * StatsOut
 */
export type StatsOut = {
    /**
     * Today
     */
    today: string;
    /**
     * Scores
     */
    scores: Array<ScoreOut>;
    /**
     * Answered
     */
    answered: Array<DayCountOut>;
    /**
     * Due
     */
    due: Array<DayCountOut>;
};

/**
 * StreakOut
 */
export type StreakOut = {
    /**
     * Days
     */
    days: number;
    /**
     * Today
     */
    today: boolean;
    /**
     * Best
     */
    best: number;
};

/**
 * TopicMapOut
 */
export type TopicMapOut = {
    /**
     * Message
     */
    message: string;
    /**
     * Untagged
     */
    untagged: number;
    job: JobOut | null;
};

/**
 * TopicOut
 */
export type TopicOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Tags
     */
    tags: Array<string>;
    /**
     * Chunk Count
     */
    chunk_count: number;
    /**
     * Question Count
     */
    question_count: number;
    /**
     * Accepted Count
     */
    accepted_count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WorkerOut
 */
export type WorkerOut = {
    /**
     * Running
     *
     * Whether a worker, or `make ingest` or `make generate`, is running
     */
    running: boolean;
};

/**
 * XpOut
 *
 * The XP an answer earned, part by part: ten times its score, five for answering, half
 * as much again for a question that was due, five inside an interview limit, and, on the
 * day's first answer, the streak's length that day, up to ten.
 */
export type XpOut = {
    /**
     * Score
     */
    score: number;
    /**
     * Answered
     */
    answered: number;
    /**
     * Due
     */
    due: number;
    /**
     * Interview
     */
    interview: number;
    /**
     * Streak
     */
    streak: number;
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthResponses = {
    /**
     * Response Health
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type DependenciesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/deps';
};

export type DependenciesResponses = {
    /**
     * Response Dependencies
     *
     * Successful Response
     */
    200: Array<Check>;
};

export type DependenciesResponse = DependenciesResponses[keyof DependenciesResponses];

export type UploadDocumentData = {
    body: BodyUploadDocument;
    path?: never;
    query?: {
        /**
         * Ocr
         */
        ocr?: boolean;
        /**
         * Formulas
         */
        formulas?: boolean;
        /**
         * Force
         */
        force?: boolean;
    };
    url: '/documents/upload';
};

export type UploadDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadDocumentError = UploadDocumentErrors[keyof UploadDocumentErrors];

export type UploadDocumentResponses = {
    /**
     * Successful Response
     */
    202: IngestOut;
};

export type UploadDocumentResponse = UploadDocumentResponses[keyof UploadDocumentResponses];

export type AddArxivPaperData = {
    body: ArxivIn;
    path?: never;
    query?: never;
    url: '/documents/arxiv';
};

export type AddArxivPaperErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddArxivPaperError = AddArxivPaperErrors[keyof AddArxivPaperErrors];

export type AddArxivPaperResponses = {
    /**
     * Successful Response
     */
    202: IngestOut;
};

export type AddArxivPaperResponse = AddArxivPaperResponses[keyof AddArxivPaperResponses];

export type ListDocumentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/documents';
};

export type ListDocumentsResponses = {
    /**
     * Response List Documents
     *
     * Successful Response
     */
    200: Array<DocumentOut>;
};

export type ListDocumentsResponse = ListDocumentsResponses[keyof ListDocumentsResponses];

export type GetDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: number;
    };
    query?: never;
    url: '/documents/{document_id}';
};

export type GetDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDocumentError = GetDocumentErrors[keyof GetDocumentErrors];

export type GetDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentOut;
};

export type GetDocumentResponse = GetDocumentResponses[keyof GetDocumentResponses];

export type ListJobsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Kind
         */
        kind?: 'ingest' | 'generate' | 'topics' | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/jobs';
};

export type ListJobsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListJobsError = ListJobsErrors[keyof ListJobsErrors];

export type ListJobsResponses = {
    /**
     * Response List Jobs
     *
     * Successful Response
     */
    200: Array<JobOut>;
};

export type ListJobsResponse = ListJobsResponses[keyof ListJobsResponses];

export type GetJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: number;
    };
    query?: never;
    url: '/jobs/{job_id}';
};

export type GetJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetJobError = GetJobErrors[keyof GetJobErrors];

export type GetJobResponses = {
    /**
     * Successful Response
     */
    200: JobOut;
};

export type GetJobResponse = GetJobResponses[keyof GetJobResponses];

export type WorkerStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/worker';
};

export type WorkerStatusResponses = {
    /**
     * Successful Response
     */
    200: WorkerOut;
};

export type WorkerStatusResponse = WorkerStatusResponses[keyof WorkerStatusResponses];

export type SearchChunksData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Q
         *
         * Question or keywords
         */
        q: string;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Mode
         */
        mode?: 'hybrid' | 'vector' | 'keyword';
    };
    url: '/search';
};

export type SearchChunksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchChunksError = SearchChunksErrors[keyof SearchChunksErrors];

export type SearchChunksResponses = {
    /**
     * Successful Response
     */
    200: SearchOut;
};

export type SearchChunksResponse = SearchChunksResponses[keyof SearchChunksResponses];

export type GenerateQuestionsData = {
    body: GenerateIn;
    path?: never;
    query?: never;
    url: '/questions/generate';
};

export type GenerateQuestionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateQuestionsError = GenerateQuestionsErrors[keyof GenerateQuestionsErrors];

export type GenerateQuestionsResponses = {
    /**
     * Successful Response
     */
    202: GenerateOut;
};

export type GenerateQuestionsResponse = GenerateQuestionsResponses[keyof GenerateQuestionsResponses];

export type ListQuestionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Status
         *
         * Only questions in this state
         */
        status?: 'accepted' | 'rejected' | 'retired' | null;
        /**
         * Topic Id
         *
         * Only questions under this topic
         */
        topic_id?: number | null;
        /**
         * Style
         *
         * Only questions of this shape
         */
        style?: 'intuition' | 'why_how' | 'compare' | 'tradeoffs' | 'failure_modes' | 'connection' | 'paper' | null;
        /**
         * Difficulty
         */
        difficulty?: number | null;
        /**
         * Document Id
         *
         * Only questions from this source
         */
        document_id?: number | null;
        /**
         * Source Updated
         *
         * Only questions whose sources a later ingestion replaced
         */
        source_updated?: boolean | null;
        /**
         * Rating
         *
         * Only questions whose latest rating is good or poor, or never rated
         */
        rating?: 'good' | 'poor' | 'unrated' | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/questions';
};

export type ListQuestionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListQuestionsError = ListQuestionsErrors[keyof ListQuestionsErrors];

export type ListQuestionsResponses = {
    /**
     * Successful Response
     */
    200: QuestionsOut;
};

export type ListQuestionsResponse = ListQuestionsResponses[keyof ListQuestionsResponses];

export type GetQuestionData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: number;
    };
    query?: never;
    url: '/questions/{question_id}';
};

export type GetQuestionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetQuestionError = GetQuestionErrors[keyof GetQuestionErrors];

export type GetQuestionResponses = {
    /**
     * Successful Response
     */
    200: QuestionDetailOut;
};

export type GetQuestionResponse = GetQuestionResponses[keyof GetQuestionResponses];

export type EditQuestionData = {
    body: QuestionEditIn;
    path: {
        /**
         * Question Id
         */
        question_id: number;
    };
    query?: never;
    url: '/questions/{question_id}';
};

export type EditQuestionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditQuestionError = EditQuestionErrors[keyof EditQuestionErrors];

export type EditQuestionResponses = {
    /**
     * Successful Response
     */
    200: QuestionDetailOut;
};

export type EditQuestionResponse = EditQuestionResponses[keyof EditQuestionResponses];

export type ListTopicsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/topics';
};

export type ListTopicsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListTopicsError = ListTopicsErrors[keyof ListTopicsErrors];

export type ListTopicsResponses = {
    /**
     * Response List Topics
     *
     * Successful Response
     */
    200: Array<TopicOut>;
};

export type ListTopicsResponse = ListTopicsResponses[keyof ListTopicsResponses];

export type BuildTopicMapData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/topics/build';
};

export type BuildTopicMapResponses = {
    /**
     * Successful Response
     */
    202: TopicMapOut;
};

export type BuildTopicMapResponse = BuildTopicMapResponses[keyof BuildTopicMapResponses];

export type ListAttemptsData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: number;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/questions/{question_id}/attempts';
};

export type ListAttemptsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAttemptsError = ListAttemptsErrors[keyof ListAttemptsErrors];

export type ListAttemptsResponses = {
    /**
     * Response List Attempts
     *
     * Successful Response
     */
    200: Array<AttemptOut>;
};

export type ListAttemptsResponse = ListAttemptsResponses[keyof ListAttemptsResponses];

export type AnswerQuestionData = {
    body: AnswerIn;
    path: {
        /**
         * Question Id
         */
        question_id: number;
    };
    query?: never;
    url: '/questions/{question_id}/attempts';
};

export type AnswerQuestionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnswerQuestionError = AnswerQuestionErrors[keyof AnswerQuestionErrors];

export type AnswerQuestionResponses = {
    /**
     * Successful Response
     */
    201: AttemptOut;
};

export type AnswerQuestionResponse = AnswerQuestionResponses[keyof AnswerQuestionResponses];

export type GradeAgainData = {
    body?: never;
    path: {
        /**
         * Attempt Id
         */
        attempt_id: number;
    };
    query?: never;
    url: '/attempts/{attempt_id}/grades';
};

export type GradeAgainErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GradeAgainError = GradeAgainErrors[keyof GradeAgainErrors];

export type GradeAgainResponses = {
    /**
     * Successful Response
     */
    201: AttemptOut;
};

export type GradeAgainResponse = GradeAgainResponses[keyof GradeAgainResponses];

export type GetAttemptData = {
    body?: never;
    path: {
        /**
         * Attempt Id
         */
        attempt_id: number;
    };
    query?: never;
    url: '/attempts/{attempt_id}';
};

export type GetAttemptErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAttemptError = GetAttemptErrors[keyof GetAttemptErrors];

export type GetAttemptResponses = {
    /**
     * Successful Response
     */
    200: AttemptOut;
};

export type GetAttemptResponse = GetAttemptResponses[keyof GetAttemptResponses];

export type PracticeNextData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/practice/next';
};

export type PracticeNextResponses = {
    /**
     * Successful Response
     */
    200: PracticeOut;
};

export type PracticeNextResponse = PracticeNextResponses[keyof PracticeNextResponses];

export type PracticeProgressData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/practice/progress';
};

export type PracticeProgressResponses = {
    /**
     * Successful Response
     */
    200: ProgressOut;
};

export type PracticeProgressResponse = PracticeProgressResponses[keyof PracticeProgressResponses];

export type PracticeMapData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/practice/map';
};

export type PracticeMapResponses = {
    /**
     * Successful Response
     */
    200: MapOut;
};

export type PracticeMapResponse = PracticeMapResponses[keyof PracticeMapResponses];

export type PracticeStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/practice/stats';
};

export type PracticeStatsResponses = {
    /**
     * Successful Response
     */
    200: StatsOut;
};

export type PracticeStatsResponse = PracticeStatsResponses[keyof PracticeStatsResponses];

export type AddRatingData = {
    body: RatingIn;
    path?: never;
    query?: never;
    url: '/ratings';
};

export type AddRatingErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddRatingError = AddRatingErrors[keyof AddRatingErrors];

export type AddRatingResponses = {
    /**
     * Successful Response
     */
    201: RatingOut;
};

export type AddRatingResponse = AddRatingResponses[keyof AddRatingResponses];
