from pathlib import Path

import pytest

pytest.importorskip("bs4")
pytest.importorskip("docling")
from app.ingest.arxiv_html import clean_latexml, parse_arxiv_html  # noqa: E402

# A trimmed copy of the LaTeXML markup arxiv.org serves for 1706.03762
PAGE = (Path(__file__).parent / "fixtures" / "latexml_paper.html").read_text(encoding="utf-8")
URL = "https://arxiv.org/html/1706.03762v7"


def test_only_the_abstract_and_sections_are_kept() -> None:
    body, _ = clean_latexml(PAGE)

    assert "The dominant sequence transduction models" in body
    for removed in (
        "Permission is granted",
        "Attention Is All You Need",
        "Ashish Vaswani",
        "Kyunghyun Cho",
        "Generated by LaTeXML",
        "<nav",
        "<img",
    ):
        assert removed not in body


def test_math_becomes_latex() -> None:
    body, _ = clean_latexml(PAGE)

    assert "compute a state $h_{t}$ from $h_{t-1}$" in body
    equation = r"$$\mathrm{Attention}(Q,K,V)=\mathrm{softmax}(\frac{QK^{T}}{\sqrt{d_{k}}})V$$"
    assert f"<p>{equation} (1)</p>" in body
    assert "<math" not in body


def test_notes_figures_and_references_become_plain_text() -> None:
    body, _ = clean_latexml(PAGE)

    # Citations and cross-references read as in the paper, without a space before ")".
    assert "Recurrent models [13, 7] compute" in body
    assert "(Figure 1). The model has two parts:" in body
    assert "<a " not in body and "<cite" not in body
    # The footnote follows its paragraph instead of interrupting the sentence.
    assert "</div><p>Footnote: Equal contribution.</p>" in body
    assert "<p>Figure 1: The Transformer - model architecture.</p>" in body
    assert "<p>Table 2: BLEU scores on newstest2014.</p><table" in body
    # List items get a marker from the parser; the bullet character would repeat it.
    assert "•" not in body


def test_headings_map_to_their_section_ids() -> None:
    _, anchors = clean_latexml(PAGE)

    assert anchors == {
        "Abstract": "abstract1",
        "1 Introduction": "S1",
        "3 Model Architecture": "S3",
        "3.2 Attention": "S3.SS2",
    }


def test_a_page_that_is_not_a_latexml_paper_is_rejected() -> None:
    with pytest.raises(ValueError, match="not a LaTeXML paper"):
        clean_latexml("<html><body><p>Access denied</p></body></html>")


def test_the_paper_becomes_blocks_with_sections_and_anchors() -> None:
    parsed = parse_arxiv_html(PAGE, title="Attention Is All You Need", url=URL)

    assert (parsed.title, parsed.locator, parsed.details) == (
        "Attention Is All You Need",
        None,
        {"source": URL},
    )
    intro = ("1 Introduction",)
    attention = ("3 Model Architecture", "3.2 Attention")
    assert [(b.headings, b.anchor, sorted(b.content_types), b.text) for b in parsed.blocks] == [
        (
            ("Abstract",),
            "abstract1",
            ["text"],
            "The dominant sequence transduction models are based on recurrent networks.",
        ),
        (
            intro,
            "S1",
            ["formula", "text"],
            "Recurrent models [13, 7] compute a state $h_{t}$ from $h_{t-1}$ (Figure 1). "
            "The model has two parts:",
        ),
        (intro, "S1", ["text"], "Footnote: Equal contribution."),
        (
            intro,
            "S1",
            ["text"],
            "- an encoder that reads the input,\n- a decoder that writes the output.",
        ),
        (
            ("3 Model Architecture",),
            "S3",
            ["text"],
            "Figure 1: The Transformer - model architecture.",
        ),
        (attention, "S3.SS2", ["text"], "Scaled dot-product attention is computed as"),
        (
            attention,
            "S3.SS2",
            ["formula", "text"],
            r"$$\mathrm{Attention}(Q,K,V)=\mathrm{softmax}(\frac{QK^{T}}{\sqrt{d_{k}}})V$$ (1)",
        ),
        (attention, "S3.SS2", ["text"], "Table 2: BLEU scores on newstest2014."),
        (
            attention,
            "S3.SS2",
            ["table"],
            "| Model | EN-DE |\n| - | - |\n| Transformer (base) | 27.3 |",
        ),
    ]


def test_a_paper_without_text_is_rejected() -> None:
    empty = "<html><body><article class='ltx_document'><h1>Title</h1></article></body></html>"
    with pytest.raises(ValueError, match="no text found"):
        parse_arxiv_html(empty, title="Title", url=URL)
